<?php
/**
 * BinanceApi
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * External Backend
 *
 * External API
 *
 * The version of the OpenAPI document: 1.15
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\FormDataProcessor;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * BinanceApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BinanceApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'binanceControllerExecuteTradingWorkflow' => [
            'application/json',
        ],
        'binanceControllerGetAveragePrice' => [
            'application/json',
        ],
        'binanceControllerGetAveragePrices' => [
            'application/json',
        ],
        'binanceControllerGetCommonAveragePrices' => [
            'application/json',
        ],
        'binanceControllerGetWithdrawFee' => [
            'application/json',
        ],
        'binanceControllerValidateSymbol' => [
            'application/json',
        ],
        'binanceControllerWithdrawToFireblocks' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation binanceControllerExecuteTradingWorkflow
     *
     * @param  \OpenAPI\Client\Model\BinanceWorkflowConfigDto $binance_workflow_config_dto binance_workflow_config_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerExecuteTradingWorkflow'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\BinanceWorkflowResponseDto
     */
    public function binanceControllerExecuteTradingWorkflow($binance_workflow_config_dto, string $contentType = self::contentTypes['binanceControllerExecuteTradingWorkflow'][0])
    {
        list($response) = $this->binanceControllerExecuteTradingWorkflowWithHttpInfo($binance_workflow_config_dto, $contentType);
        return $response;
    }

    /**
     * Operation binanceControllerExecuteTradingWorkflowWithHttpInfo
     *
     * @param  \OpenAPI\Client\Model\BinanceWorkflowConfigDto $binance_workflow_config_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerExecuteTradingWorkflow'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\BinanceWorkflowResponseDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function binanceControllerExecuteTradingWorkflowWithHttpInfo($binance_workflow_config_dto, string $contentType = self::contentTypes['binanceControllerExecuteTradingWorkflow'][0])
    {
        $request = $this->binanceControllerExecuteTradingWorkflowRequest($binance_workflow_config_dto, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\BinanceWorkflowResponseDto',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\BinanceWorkflowResponseDto',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\BinanceWorkflowResponseDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation binanceControllerExecuteTradingWorkflowAsync
     *
     * @param  \OpenAPI\Client\Model\BinanceWorkflowConfigDto $binance_workflow_config_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerExecuteTradingWorkflow'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function binanceControllerExecuteTradingWorkflowAsync($binance_workflow_config_dto, string $contentType = self::contentTypes['binanceControllerExecuteTradingWorkflow'][0])
    {
        return $this->binanceControllerExecuteTradingWorkflowAsyncWithHttpInfo($binance_workflow_config_dto, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation binanceControllerExecuteTradingWorkflowAsyncWithHttpInfo
     *
     * @param  \OpenAPI\Client\Model\BinanceWorkflowConfigDto $binance_workflow_config_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerExecuteTradingWorkflow'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function binanceControllerExecuteTradingWorkflowAsyncWithHttpInfo($binance_workflow_config_dto, string $contentType = self::contentTypes['binanceControllerExecuteTradingWorkflow'][0])
    {
        $returnType = '\OpenAPI\Client\Model\BinanceWorkflowResponseDto';
        $request = $this->binanceControllerExecuteTradingWorkflowRequest($binance_workflow_config_dto, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'binanceControllerExecuteTradingWorkflow'
     *
     * @param  \OpenAPI\Client\Model\BinanceWorkflowConfigDto $binance_workflow_config_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerExecuteTradingWorkflow'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function binanceControllerExecuteTradingWorkflowRequest($binance_workflow_config_dto, string $contentType = self::contentTypes['binanceControllerExecuteTradingWorkflow'][0])
    {

        // verify the required parameter 'binance_workflow_config_dto' is set
        if ($binance_workflow_config_dto === null || (is_array($binance_workflow_config_dto) && count($binance_workflow_config_dto) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $binance_workflow_config_dto when calling binanceControllerExecuteTradingWorkflow'
            );
        }


        $resourcePath = '/binance/workflow/execute';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($binance_workflow_config_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($binance_workflow_config_dto));
            } else {
                $httpBody = $binance_workflow_config_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation binanceControllerGetAveragePrice
     *
     * @param  string $symbol Trading pair symbol (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerGetAveragePrice'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\BinanceControllerGetAveragePrice200Response
     */
    public function binanceControllerGetAveragePrice($symbol, string $contentType = self::contentTypes['binanceControllerGetAveragePrice'][0])
    {
        list($response) = $this->binanceControllerGetAveragePriceWithHttpInfo($symbol, $contentType);
        return $response;
    }

    /**
     * Operation binanceControllerGetAveragePriceWithHttpInfo
     *
     * @param  string $symbol Trading pair symbol (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerGetAveragePrice'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\BinanceControllerGetAveragePrice200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function binanceControllerGetAveragePriceWithHttpInfo($symbol, string $contentType = self::contentTypes['binanceControllerGetAveragePrice'][0])
    {
        $request = $this->binanceControllerGetAveragePriceRequest($symbol, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\BinanceControllerGetAveragePrice200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\BinanceControllerGetAveragePrice200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\BinanceControllerGetAveragePrice200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation binanceControllerGetAveragePriceAsync
     *
     * @param  string $symbol Trading pair symbol (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerGetAveragePrice'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function binanceControllerGetAveragePriceAsync($symbol, string $contentType = self::contentTypes['binanceControllerGetAveragePrice'][0])
    {
        return $this->binanceControllerGetAveragePriceAsyncWithHttpInfo($symbol, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation binanceControllerGetAveragePriceAsyncWithHttpInfo
     *
     * @param  string $symbol Trading pair symbol (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerGetAveragePrice'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function binanceControllerGetAveragePriceAsyncWithHttpInfo($symbol, string $contentType = self::contentTypes['binanceControllerGetAveragePrice'][0])
    {
        $returnType = '\OpenAPI\Client\Model\BinanceControllerGetAveragePrice200Response';
        $request = $this->binanceControllerGetAveragePriceRequest($symbol, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'binanceControllerGetAveragePrice'
     *
     * @param  string $symbol Trading pair symbol (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerGetAveragePrice'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function binanceControllerGetAveragePriceRequest($symbol, string $contentType = self::contentTypes['binanceControllerGetAveragePrice'][0])
    {

        // verify the required parameter 'symbol' is set
        if ($symbol === null || (is_array($symbol) && count($symbol) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $symbol when calling binanceControllerGetAveragePrice'
            );
        }


        $resourcePath = '/binance/average-price/{symbol}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($symbol !== null) {
            $resourcePath = str_replace(
                '{' . 'symbol' . '}',
                ObjectSerializer::toPathValue($symbol),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation binanceControllerGetAveragePrices
     *
     * @param  string $symbols Comma-separated list of symbols (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerGetAveragePrices'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\BinanceControllerGetAveragePrice200Response[]
     */
    public function binanceControllerGetAveragePrices($symbols, string $contentType = self::contentTypes['binanceControllerGetAveragePrices'][0])
    {
        list($response) = $this->binanceControllerGetAveragePricesWithHttpInfo($symbols, $contentType);
        return $response;
    }

    /**
     * Operation binanceControllerGetAveragePricesWithHttpInfo
     *
     * @param  string $symbols Comma-separated list of symbols (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerGetAveragePrices'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\BinanceControllerGetAveragePrice200Response[], HTTP status code, HTTP response headers (array of strings)
     */
    public function binanceControllerGetAveragePricesWithHttpInfo($symbols, string $contentType = self::contentTypes['binanceControllerGetAveragePrices'][0])
    {
        $request = $this->binanceControllerGetAveragePricesRequest($symbols, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\BinanceControllerGetAveragePrice200Response[]',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\BinanceControllerGetAveragePrice200Response[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\BinanceControllerGetAveragePrice200Response[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation binanceControllerGetAveragePricesAsync
     *
     * @param  string $symbols Comma-separated list of symbols (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerGetAveragePrices'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function binanceControllerGetAveragePricesAsync($symbols, string $contentType = self::contentTypes['binanceControllerGetAveragePrices'][0])
    {
        return $this->binanceControllerGetAveragePricesAsyncWithHttpInfo($symbols, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation binanceControllerGetAveragePricesAsyncWithHttpInfo
     *
     * @param  string $symbols Comma-separated list of symbols (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerGetAveragePrices'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function binanceControllerGetAveragePricesAsyncWithHttpInfo($symbols, string $contentType = self::contentTypes['binanceControllerGetAveragePrices'][0])
    {
        $returnType = '\OpenAPI\Client\Model\BinanceControllerGetAveragePrice200Response[]';
        $request = $this->binanceControllerGetAveragePricesRequest($symbols, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'binanceControllerGetAveragePrices'
     *
     * @param  string $symbols Comma-separated list of symbols (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerGetAveragePrices'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function binanceControllerGetAveragePricesRequest($symbols, string $contentType = self::contentTypes['binanceControllerGetAveragePrices'][0])
    {

        // verify the required parameter 'symbols' is set
        if ($symbols === null || (is_array($symbols) && count($symbols) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $symbols when calling binanceControllerGetAveragePrices'
            );
        }


        $resourcePath = '/binance/average-prices';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $symbols,
            'symbols', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation binanceControllerGetCommonAveragePrices
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerGetCommonAveragePrices'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\BinanceControllerGetAveragePrice200Response[]
     */
    public function binanceControllerGetCommonAveragePrices(string $contentType = self::contentTypes['binanceControllerGetCommonAveragePrices'][0])
    {
        list($response) = $this->binanceControllerGetCommonAveragePricesWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation binanceControllerGetCommonAveragePricesWithHttpInfo
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerGetCommonAveragePrices'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\BinanceControllerGetAveragePrice200Response[], HTTP status code, HTTP response headers (array of strings)
     */
    public function binanceControllerGetCommonAveragePricesWithHttpInfo(string $contentType = self::contentTypes['binanceControllerGetCommonAveragePrices'][0])
    {
        $request = $this->binanceControllerGetCommonAveragePricesRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\BinanceControllerGetAveragePrice200Response[]',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\BinanceControllerGetAveragePrice200Response[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\BinanceControllerGetAveragePrice200Response[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation binanceControllerGetCommonAveragePricesAsync
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerGetCommonAveragePrices'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function binanceControllerGetCommonAveragePricesAsync(string $contentType = self::contentTypes['binanceControllerGetCommonAveragePrices'][0])
    {
        return $this->binanceControllerGetCommonAveragePricesAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation binanceControllerGetCommonAveragePricesAsyncWithHttpInfo
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerGetCommonAveragePrices'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function binanceControllerGetCommonAveragePricesAsyncWithHttpInfo(string $contentType = self::contentTypes['binanceControllerGetCommonAveragePrices'][0])
    {
        $returnType = '\OpenAPI\Client\Model\BinanceControllerGetAveragePrice200Response[]';
        $request = $this->binanceControllerGetCommonAveragePricesRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'binanceControllerGetCommonAveragePrices'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerGetCommonAveragePrices'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function binanceControllerGetCommonAveragePricesRequest(string $contentType = self::contentTypes['binanceControllerGetCommonAveragePrices'][0])
    {


        $resourcePath = '/binance/common-average-prices';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation binanceControllerGetWithdrawFee
     *
     * @param  string $currency Currency to get withdraw fee for (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerGetWithdrawFee'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\BinanceControllerGetWithdrawFee200Response
     */
    public function binanceControllerGetWithdrawFee($currency, string $contentType = self::contentTypes['binanceControllerGetWithdrawFee'][0])
    {
        list($response) = $this->binanceControllerGetWithdrawFeeWithHttpInfo($currency, $contentType);
        return $response;
    }

    /**
     * Operation binanceControllerGetWithdrawFeeWithHttpInfo
     *
     * @param  string $currency Currency to get withdraw fee for (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerGetWithdrawFee'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\BinanceControllerGetWithdrawFee200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function binanceControllerGetWithdrawFeeWithHttpInfo($currency, string $contentType = self::contentTypes['binanceControllerGetWithdrawFee'][0])
    {
        $request = $this->binanceControllerGetWithdrawFeeRequest($currency, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\BinanceControllerGetWithdrawFee200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\BinanceControllerGetWithdrawFee200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\BinanceControllerGetWithdrawFee200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation binanceControllerGetWithdrawFeeAsync
     *
     * @param  string $currency Currency to get withdraw fee for (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerGetWithdrawFee'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function binanceControllerGetWithdrawFeeAsync($currency, string $contentType = self::contentTypes['binanceControllerGetWithdrawFee'][0])
    {
        return $this->binanceControllerGetWithdrawFeeAsyncWithHttpInfo($currency, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation binanceControllerGetWithdrawFeeAsyncWithHttpInfo
     *
     * @param  string $currency Currency to get withdraw fee for (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerGetWithdrawFee'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function binanceControllerGetWithdrawFeeAsyncWithHttpInfo($currency, string $contentType = self::contentTypes['binanceControllerGetWithdrawFee'][0])
    {
        $returnType = '\OpenAPI\Client\Model\BinanceControllerGetWithdrawFee200Response';
        $request = $this->binanceControllerGetWithdrawFeeRequest($currency, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'binanceControllerGetWithdrawFee'
     *
     * @param  string $currency Currency to get withdraw fee for (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerGetWithdrawFee'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function binanceControllerGetWithdrawFeeRequest($currency, string $contentType = self::contentTypes['binanceControllerGetWithdrawFee'][0])
    {

        // verify the required parameter 'currency' is set
        if ($currency === null || (is_array($currency) && count($currency) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $currency when calling binanceControllerGetWithdrawFee'
            );
        }


        $resourcePath = '/binance/withdraw-fee/{currency}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($currency !== null) {
            $resourcePath = str_replace(
                '{' . 'currency' . '}',
                ObjectSerializer::toPathValue($currency),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation binanceControllerValidateSymbol
     *
     * @param  string $symbol Trading pair symbol to validate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerValidateSymbol'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\BinanceControllerValidateSymbol200Response
     */
    public function binanceControllerValidateSymbol($symbol, string $contentType = self::contentTypes['binanceControllerValidateSymbol'][0])
    {
        list($response) = $this->binanceControllerValidateSymbolWithHttpInfo($symbol, $contentType);
        return $response;
    }

    /**
     * Operation binanceControllerValidateSymbolWithHttpInfo
     *
     * @param  string $symbol Trading pair symbol to validate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerValidateSymbol'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\BinanceControllerValidateSymbol200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function binanceControllerValidateSymbolWithHttpInfo($symbol, string $contentType = self::contentTypes['binanceControllerValidateSymbol'][0])
    {
        $request = $this->binanceControllerValidateSymbolRequest($symbol, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\BinanceControllerValidateSymbol200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\BinanceControllerValidateSymbol200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\BinanceControllerValidateSymbol200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation binanceControllerValidateSymbolAsync
     *
     * @param  string $symbol Trading pair symbol to validate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerValidateSymbol'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function binanceControllerValidateSymbolAsync($symbol, string $contentType = self::contentTypes['binanceControllerValidateSymbol'][0])
    {
        return $this->binanceControllerValidateSymbolAsyncWithHttpInfo($symbol, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation binanceControllerValidateSymbolAsyncWithHttpInfo
     *
     * @param  string $symbol Trading pair symbol to validate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerValidateSymbol'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function binanceControllerValidateSymbolAsyncWithHttpInfo($symbol, string $contentType = self::contentTypes['binanceControllerValidateSymbol'][0])
    {
        $returnType = '\OpenAPI\Client\Model\BinanceControllerValidateSymbol200Response';
        $request = $this->binanceControllerValidateSymbolRequest($symbol, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'binanceControllerValidateSymbol'
     *
     * @param  string $symbol Trading pair symbol to validate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerValidateSymbol'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function binanceControllerValidateSymbolRequest($symbol, string $contentType = self::contentTypes['binanceControllerValidateSymbol'][0])
    {

        // verify the required parameter 'symbol' is set
        if ($symbol === null || (is_array($symbol) && count($symbol) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $symbol when calling binanceControllerValidateSymbol'
            );
        }


        $resourcePath = '/binance/validate-symbol/{symbol}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($symbol !== null) {
            $resourcePath = str_replace(
                '{' . 'symbol' . '}',
                ObjectSerializer::toPathValue($symbol),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation binanceControllerWithdrawToFireblocks
     *
     * @param  \OpenAPI\Client\Model\BinanceWithdrawRequestDto $binance_withdraw_request_dto binance_withdraw_request_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerWithdrawToFireblocks'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\BinanceWithdrawResponseDto
     */
    public function binanceControllerWithdrawToFireblocks($binance_withdraw_request_dto, string $contentType = self::contentTypes['binanceControllerWithdrawToFireblocks'][0])
    {
        list($response) = $this->binanceControllerWithdrawToFireblocksWithHttpInfo($binance_withdraw_request_dto, $contentType);
        return $response;
    }

    /**
     * Operation binanceControllerWithdrawToFireblocksWithHttpInfo
     *
     * @param  \OpenAPI\Client\Model\BinanceWithdrawRequestDto $binance_withdraw_request_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerWithdrawToFireblocks'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\BinanceWithdrawResponseDto, HTTP status code, HTTP response headers (array of strings)
     */
    public function binanceControllerWithdrawToFireblocksWithHttpInfo($binance_withdraw_request_dto, string $contentType = self::contentTypes['binanceControllerWithdrawToFireblocks'][0])
    {
        $request = $this->binanceControllerWithdrawToFireblocksRequest($binance_withdraw_request_dto, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\BinanceWithdrawResponseDto',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\BinanceWithdrawResponseDto',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\BinanceWithdrawResponseDto',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation binanceControllerWithdrawToFireblocksAsync
     *
     * @param  \OpenAPI\Client\Model\BinanceWithdrawRequestDto $binance_withdraw_request_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerWithdrawToFireblocks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function binanceControllerWithdrawToFireblocksAsync($binance_withdraw_request_dto, string $contentType = self::contentTypes['binanceControllerWithdrawToFireblocks'][0])
    {
        return $this->binanceControllerWithdrawToFireblocksAsyncWithHttpInfo($binance_withdraw_request_dto, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation binanceControllerWithdrawToFireblocksAsyncWithHttpInfo
     *
     * @param  \OpenAPI\Client\Model\BinanceWithdrawRequestDto $binance_withdraw_request_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerWithdrawToFireblocks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function binanceControllerWithdrawToFireblocksAsyncWithHttpInfo($binance_withdraw_request_dto, string $contentType = self::contentTypes['binanceControllerWithdrawToFireblocks'][0])
    {
        $returnType = '\OpenAPI\Client\Model\BinanceWithdrawResponseDto';
        $request = $this->binanceControllerWithdrawToFireblocksRequest($binance_withdraw_request_dto, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'binanceControllerWithdrawToFireblocks'
     *
     * @param  \OpenAPI\Client\Model\BinanceWithdrawRequestDto $binance_withdraw_request_dto (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['binanceControllerWithdrawToFireblocks'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function binanceControllerWithdrawToFireblocksRequest($binance_withdraw_request_dto, string $contentType = self::contentTypes['binanceControllerWithdrawToFireblocks'][0])
    {

        // verify the required parameter 'binance_withdraw_request_dto' is set
        if ($binance_withdraw_request_dto === null || (is_array($binance_withdraw_request_dto) && count($binance_withdraw_request_dto) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $binance_withdraw_request_dto when calling binanceControllerWithdrawToFireblocks'
            );
        }


        $resourcePath = '/binance/withdraw';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($binance_withdraw_request_dto)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($binance_withdraw_request_dto));
            } else {
                $httpBody = $binance_withdraw_request_dto;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
