<?php
/**
 * CheckoutPaymentResponseV2Dto
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API title
 *
 * API description
 *
 * The version of the OpenAPI document: 2.21
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CheckoutPaymentResponseV2Dto Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CheckoutPaymentResponseV2Dto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CheckoutPaymentResponseV2Dto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'payment_type' => 'string',
        'address' => 'string',
        'network' => 'string',
        'to_network' => 'string',
        'date' => 'string',
        'chain_logo_url' => 'string',
        'to_chain_logo_url' => 'string',
        'coin_logo_url' => 'string',
        'to_coin_logo_url' => 'string',
        'payment_id' => 'string',
        'status' => 'object',
        'amount' => 'string',
        'amount_expected' => 'string',
        'amount_paid' => 'string',
        'usd_amount' => 'string',
        'transaction_currency' => 'string',
        'processing_fee' => 'string',
        'processing_fee_usd' => 'string',
        'conversion_rate' => 'float',
        'crypto_transaction_info' => '\OpenAPI\Client\Model\PaymentResponseV2DtoCryptoTransactionInfoInner[]',
        'rate' => 'float',
        'partner_payment_id' => 'string',
        'partner_settings' => '\OpenAPI\Client\Model\SettingsResponseV2Dto'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'payment_type' => null,
        'address' => null,
        'network' => null,
        'to_network' => null,
        'date' => null,
        'chain_logo_url' => null,
        'to_chain_logo_url' => null,
        'coin_logo_url' => null,
        'to_coin_logo_url' => null,
        'payment_id' => null,
        'status' => null,
        'amount' => null,
        'amount_expected' => null,
        'amount_paid' => null,
        'usd_amount' => null,
        'transaction_currency' => null,
        'processing_fee' => null,
        'processing_fee_usd' => null,
        'conversion_rate' => null,
        'crypto_transaction_info' => null,
        'rate' => null,
        'partner_payment_id' => null,
        'partner_settings' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'payment_type' => false,
        'address' => false,
        'network' => false,
        'to_network' => false,
        'date' => false,
        'chain_logo_url' => false,
        'to_chain_logo_url' => false,
        'coin_logo_url' => false,
        'to_coin_logo_url' => false,
        'payment_id' => false,
        'status' => false,
        'amount' => false,
        'amount_expected' => false,
        'amount_paid' => false,
        'usd_amount' => false,
        'transaction_currency' => false,
        'processing_fee' => false,
        'processing_fee_usd' => false,
        'conversion_rate' => false,
        'crypto_transaction_info' => false,
        'rate' => false,
        'partner_payment_id' => false,
        'partner_settings' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'payment_type' => 'paymentType',
        'address' => 'address',
        'network' => 'network',
        'to_network' => 'toNetwork',
        'date' => 'date',
        'chain_logo_url' => 'chainLogoUrl',
        'to_chain_logo_url' => 'toChainLogoUrl',
        'coin_logo_url' => 'coinLogoUrl',
        'to_coin_logo_url' => 'toCoinLogoUrl',
        'payment_id' => 'paymentId',
        'status' => 'status',
        'amount' => 'amount',
        'amount_expected' => 'amountExpected',
        'amount_paid' => 'amountPaid',
        'usd_amount' => 'usdAmount',
        'transaction_currency' => 'transactionCurrency',
        'processing_fee' => 'processingFee',
        'processing_fee_usd' => 'processingFeeUsd',
        'conversion_rate' => 'conversionRate',
        'crypto_transaction_info' => 'cryptoTransactionInfo',
        'rate' => 'rate',
        'partner_payment_id' => 'partnerPaymentID',
        'partner_settings' => 'partnerSettings'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'payment_type' => 'setPaymentType',
        'address' => 'setAddress',
        'network' => 'setNetwork',
        'to_network' => 'setToNetwork',
        'date' => 'setDate',
        'chain_logo_url' => 'setChainLogoUrl',
        'to_chain_logo_url' => 'setToChainLogoUrl',
        'coin_logo_url' => 'setCoinLogoUrl',
        'to_coin_logo_url' => 'setToCoinLogoUrl',
        'payment_id' => 'setPaymentId',
        'status' => 'setStatus',
        'amount' => 'setAmount',
        'amount_expected' => 'setAmountExpected',
        'amount_paid' => 'setAmountPaid',
        'usd_amount' => 'setUsdAmount',
        'transaction_currency' => 'setTransactionCurrency',
        'processing_fee' => 'setProcessingFee',
        'processing_fee_usd' => 'setProcessingFeeUsd',
        'conversion_rate' => 'setConversionRate',
        'crypto_transaction_info' => 'setCryptoTransactionInfo',
        'rate' => 'setRate',
        'partner_payment_id' => 'setPartnerPaymentId',
        'partner_settings' => 'setPartnerSettings'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'payment_type' => 'getPaymentType',
        'address' => 'getAddress',
        'network' => 'getNetwork',
        'to_network' => 'getToNetwork',
        'date' => 'getDate',
        'chain_logo_url' => 'getChainLogoUrl',
        'to_chain_logo_url' => 'getToChainLogoUrl',
        'coin_logo_url' => 'getCoinLogoUrl',
        'to_coin_logo_url' => 'getToCoinLogoUrl',
        'payment_id' => 'getPaymentId',
        'status' => 'getStatus',
        'amount' => 'getAmount',
        'amount_expected' => 'getAmountExpected',
        'amount_paid' => 'getAmountPaid',
        'usd_amount' => 'getUsdAmount',
        'transaction_currency' => 'getTransactionCurrency',
        'processing_fee' => 'getProcessingFee',
        'processing_fee_usd' => 'getProcessingFeeUsd',
        'conversion_rate' => 'getConversionRate',
        'crypto_transaction_info' => 'getCryptoTransactionInfo',
        'rate' => 'getRate',
        'partner_payment_id' => 'getPartnerPaymentId',
        'partner_settings' => 'getPartnerSettings'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const PAYMENT_TYPE_UNKNOWN = 'UNKNOWN';
    public const PAYMENT_TYPE_DEPOSIT = 'DEPOSIT';
    public const PAYMENT_TYPE_WITHDRAWAL = 'WITHDRAWAL';
    public const PAYMENT_TYPE_CHECKOUT = 'CHECKOUT';
    public const PAYMENT_TYPE_MANUAL_DEPOSIT = 'MANUAL_DEPOSIT';
    public const PAYMENT_TYPE_MANUAL_WITHDRAWAL = 'MANUAL_WITHDRAWAL';
    public const PAYMENT_TYPE_AUTO_CONVERSION_DEPOSIT = 'AUTO_CONVERSION_DEPOSIT';
    public const PAYMENT_TYPE_AUTO_CONVERSION_WITHDRAWAL = 'AUTO_CONVERSION_WITHDRAWAL';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPaymentTypeAllowableValues()
    {
        return [
            self::PAYMENT_TYPE_UNKNOWN,
            self::PAYMENT_TYPE_DEPOSIT,
            self::PAYMENT_TYPE_WITHDRAWAL,
            self::PAYMENT_TYPE_CHECKOUT,
            self::PAYMENT_TYPE_MANUAL_DEPOSIT,
            self::PAYMENT_TYPE_MANUAL_WITHDRAWAL,
            self::PAYMENT_TYPE_AUTO_CONVERSION_DEPOSIT,
            self::PAYMENT_TYPE_AUTO_CONVERSION_WITHDRAWAL,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('payment_type', $data ?? [], null);
        $this->setIfExists('address', $data ?? [], null);
        $this->setIfExists('network', $data ?? [], null);
        $this->setIfExists('to_network', $data ?? [], null);
        $this->setIfExists('date', $data ?? [], null);
        $this->setIfExists('chain_logo_url', $data ?? [], null);
        $this->setIfExists('to_chain_logo_url', $data ?? [], null);
        $this->setIfExists('coin_logo_url', $data ?? [], null);
        $this->setIfExists('to_coin_logo_url', $data ?? [], null);
        $this->setIfExists('payment_id', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('amount', $data ?? [], null);
        $this->setIfExists('amount_expected', $data ?? [], null);
        $this->setIfExists('amount_paid', $data ?? [], null);
        $this->setIfExists('usd_amount', $data ?? [], null);
        $this->setIfExists('transaction_currency', $data ?? [], null);
        $this->setIfExists('processing_fee', $data ?? [], null);
        $this->setIfExists('processing_fee_usd', $data ?? [], null);
        $this->setIfExists('conversion_rate', $data ?? [], null);
        $this->setIfExists('crypto_transaction_info', $data ?? [], null);
        $this->setIfExists('rate', $data ?? [], null);
        $this->setIfExists('partner_payment_id', $data ?? [], null);
        $this->setIfExists('partner_settings', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['payment_type'] === null) {
            $invalidProperties[] = "'payment_type' can't be null";
        }
        $allowedValues = $this->getPaymentTypeAllowableValues();
        if (!is_null($this->container['payment_type']) && !in_array($this->container['payment_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'payment_type', must be one of '%s'",
                $this->container['payment_type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['address'] === null) {
            $invalidProperties[] = "'address' can't be null";
        }
        if ($this->container['network'] === null) {
            $invalidProperties[] = "'network' can't be null";
        }
        if ($this->container['date'] === null) {
            $invalidProperties[] = "'date' can't be null";
        }
        if ($this->container['chain_logo_url'] === null) {
            $invalidProperties[] = "'chain_logo_url' can't be null";
        }
        if ($this->container['coin_logo_url'] === null) {
            $invalidProperties[] = "'coin_logo_url' can't be null";
        }
        if ($this->container['payment_id'] === null) {
            $invalidProperties[] = "'payment_id' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['amount'] === null) {
            $invalidProperties[] = "'amount' can't be null";
        }
        if ($this->container['amount_expected'] === null) {
            $invalidProperties[] = "'amount_expected' can't be null";
        }
        if ($this->container['amount_paid'] === null) {
            $invalidProperties[] = "'amount_paid' can't be null";
        }
        if ($this->container['usd_amount'] === null) {
            $invalidProperties[] = "'usd_amount' can't be null";
        }
        if ($this->container['transaction_currency'] === null) {
            $invalidProperties[] = "'transaction_currency' can't be null";
        }
        if ($this->container['processing_fee'] === null) {
            $invalidProperties[] = "'processing_fee' can't be null";
        }
        if ($this->container['processing_fee_usd'] === null) {
            $invalidProperties[] = "'processing_fee_usd' can't be null";
        }
        if ($this->container['conversion_rate'] === null) {
            $invalidProperties[] = "'conversion_rate' can't be null";
        }
        if ($this->container['crypto_transaction_info'] === null) {
            $invalidProperties[] = "'crypto_transaction_info' can't be null";
        }
        if ($this->container['rate'] === null) {
            $invalidProperties[] = "'rate' can't be null";
        }
        if ($this->container['partner_settings'] === null) {
            $invalidProperties[] = "'partner_settings' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets payment_type
     *
     * @return string
     */
    public function getPaymentType()
    {
        return $this->container['payment_type'];
    }

    /**
     * Sets payment_type
     *
     * @param string $payment_type payment_type
     *
     * @return self
     */
    public function setPaymentType($payment_type)
    {
        if (is_null($payment_type)) {
            throw new \InvalidArgumentException('non-nullable payment_type cannot be null');
        }
        $allowedValues = $this->getPaymentTypeAllowableValues();
        if (!in_array($payment_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'payment_type', must be one of '%s'",
                    $payment_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['payment_type'] = $payment_type;

        return $this;
    }

    /**
     * Gets address
     *
     * @return string
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param string $address address
     *
     * @return self
     */
    public function setAddress($address)
    {
        if (is_null($address)) {
            throw new \InvalidArgumentException('non-nullable address cannot be null');
        }
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets network
     *
     * @return string
     */
    public function getNetwork()
    {
        return $this->container['network'];
    }

    /**
     * Sets network
     *
     * @param string $network network
     *
     * @return self
     */
    public function setNetwork($network)
    {
        if (is_null($network)) {
            throw new \InvalidArgumentException('non-nullable network cannot be null');
        }
        $this->container['network'] = $network;

        return $this;
    }

    /**
     * Gets to_network
     *
     * @return string|null
     */
    public function getToNetwork()
    {
        return $this->container['to_network'];
    }

    /**
     * Sets to_network
     *
     * @param string|null $to_network to_network
     *
     * @return self
     */
    public function setToNetwork($to_network)
    {
        if (is_null($to_network)) {
            throw new \InvalidArgumentException('non-nullable to_network cannot be null');
        }
        $this->container['to_network'] = $to_network;

        return $this;
    }

    /**
     * Gets date
     *
     * @return string
     */
    public function getDate()
    {
        return $this->container['date'];
    }

    /**
     * Sets date
     *
     * @param string $date date
     *
     * @return self
     */
    public function setDate($date)
    {
        if (is_null($date)) {
            throw new \InvalidArgumentException('non-nullable date cannot be null');
        }
        $this->container['date'] = $date;

        return $this;
    }

    /**
     * Gets chain_logo_url
     *
     * @return string
     */
    public function getChainLogoUrl()
    {
        return $this->container['chain_logo_url'];
    }

    /**
     * Sets chain_logo_url
     *
     * @param string $chain_logo_url chain_logo_url
     *
     * @return self
     */
    public function setChainLogoUrl($chain_logo_url)
    {
        if (is_null($chain_logo_url)) {
            throw new \InvalidArgumentException('non-nullable chain_logo_url cannot be null');
        }
        $this->container['chain_logo_url'] = $chain_logo_url;

        return $this;
    }

    /**
     * Gets to_chain_logo_url
     *
     * @return string|null
     */
    public function getToChainLogoUrl()
    {
        return $this->container['to_chain_logo_url'];
    }

    /**
     * Sets to_chain_logo_url
     *
     * @param string|null $to_chain_logo_url to_chain_logo_url
     *
     * @return self
     */
    public function setToChainLogoUrl($to_chain_logo_url)
    {
        if (is_null($to_chain_logo_url)) {
            throw new \InvalidArgumentException('non-nullable to_chain_logo_url cannot be null');
        }
        $this->container['to_chain_logo_url'] = $to_chain_logo_url;

        return $this;
    }

    /**
     * Gets coin_logo_url
     *
     * @return string
     */
    public function getCoinLogoUrl()
    {
        return $this->container['coin_logo_url'];
    }

    /**
     * Sets coin_logo_url
     *
     * @param string $coin_logo_url coin_logo_url
     *
     * @return self
     */
    public function setCoinLogoUrl($coin_logo_url)
    {
        if (is_null($coin_logo_url)) {
            throw new \InvalidArgumentException('non-nullable coin_logo_url cannot be null');
        }
        $this->container['coin_logo_url'] = $coin_logo_url;

        return $this;
    }

    /**
     * Gets to_coin_logo_url
     *
     * @return string|null
     */
    public function getToCoinLogoUrl()
    {
        return $this->container['to_coin_logo_url'];
    }

    /**
     * Sets to_coin_logo_url
     *
     * @param string|null $to_coin_logo_url to_coin_logo_url
     *
     * @return self
     */
    public function setToCoinLogoUrl($to_coin_logo_url)
    {
        if (is_null($to_coin_logo_url)) {
            throw new \InvalidArgumentException('non-nullable to_coin_logo_url cannot be null');
        }
        $this->container['to_coin_logo_url'] = $to_coin_logo_url;

        return $this;
    }

    /**
     * Gets payment_id
     *
     * @return string
     */
    public function getPaymentId()
    {
        return $this->container['payment_id'];
    }

    /**
     * Sets payment_id
     *
     * @param string $payment_id payment_id
     *
     * @return self
     */
    public function setPaymentId($payment_id)
    {
        if (is_null($payment_id)) {
            throw new \InvalidArgumentException('non-nullable payment_id cannot be null');
        }
        $this->container['payment_id'] = $payment_id;

        return $this;
    }

    /**
     * Gets status
     *
     * @return object
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param object $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return string
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param string $amount amount
     *
     * @return self
     */
    public function setAmount($amount)
    {
        if (is_null($amount)) {
            throw new \InvalidArgumentException('non-nullable amount cannot be null');
        }
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets amount_expected
     *
     * @return string
     */
    public function getAmountExpected()
    {
        return $this->container['amount_expected'];
    }

    /**
     * Sets amount_expected
     *
     * @param string $amount_expected amount_expected
     *
     * @return self
     */
    public function setAmountExpected($amount_expected)
    {
        if (is_null($amount_expected)) {
            throw new \InvalidArgumentException('non-nullable amount_expected cannot be null');
        }
        $this->container['amount_expected'] = $amount_expected;

        return $this;
    }

    /**
     * Gets amount_paid
     *
     * @return string
     */
    public function getAmountPaid()
    {
        return $this->container['amount_paid'];
    }

    /**
     * Sets amount_paid
     *
     * @param string $amount_paid amount_paid
     *
     * @return self
     */
    public function setAmountPaid($amount_paid)
    {
        if (is_null($amount_paid)) {
            throw new \InvalidArgumentException('non-nullable amount_paid cannot be null');
        }
        $this->container['amount_paid'] = $amount_paid;

        return $this;
    }

    /**
     * Gets usd_amount
     *
     * @return string
     */
    public function getUsdAmount()
    {
        return $this->container['usd_amount'];
    }

    /**
     * Sets usd_amount
     *
     * @param string $usd_amount usd_amount
     *
     * @return self
     */
    public function setUsdAmount($usd_amount)
    {
        if (is_null($usd_amount)) {
            throw new \InvalidArgumentException('non-nullable usd_amount cannot be null');
        }
        $this->container['usd_amount'] = $usd_amount;

        return $this;
    }

    /**
     * Gets transaction_currency
     *
     * @return string
     */
    public function getTransactionCurrency()
    {
        return $this->container['transaction_currency'];
    }

    /**
     * Sets transaction_currency
     *
     * @param string $transaction_currency transaction_currency
     *
     * @return self
     */
    public function setTransactionCurrency($transaction_currency)
    {
        if (is_null($transaction_currency)) {
            throw new \InvalidArgumentException('non-nullable transaction_currency cannot be null');
        }
        $this->container['transaction_currency'] = $transaction_currency;

        return $this;
    }

    /**
     * Gets processing_fee
     *
     * @return string
     */
    public function getProcessingFee()
    {
        return $this->container['processing_fee'];
    }

    /**
     * Sets processing_fee
     *
     * @param string $processing_fee processing_fee
     *
     * @return self
     */
    public function setProcessingFee($processing_fee)
    {
        if (is_null($processing_fee)) {
            throw new \InvalidArgumentException('non-nullable processing_fee cannot be null');
        }
        $this->container['processing_fee'] = $processing_fee;

        return $this;
    }

    /**
     * Gets processing_fee_usd
     *
     * @return string
     */
    public function getProcessingFeeUsd()
    {
        return $this->container['processing_fee_usd'];
    }

    /**
     * Sets processing_fee_usd
     *
     * @param string $processing_fee_usd processing_fee_usd
     *
     * @return self
     */
    public function setProcessingFeeUsd($processing_fee_usd)
    {
        if (is_null($processing_fee_usd)) {
            throw new \InvalidArgumentException('non-nullable processing_fee_usd cannot be null');
        }
        $this->container['processing_fee_usd'] = $processing_fee_usd;

        return $this;
    }

    /**
     * Gets conversion_rate
     *
     * @return float
     */
    public function getConversionRate()
    {
        return $this->container['conversion_rate'];
    }

    /**
     * Sets conversion_rate
     *
     * @param float $conversion_rate conversion_rate
     *
     * @return self
     */
    public function setConversionRate($conversion_rate)
    {
        if (is_null($conversion_rate)) {
            throw new \InvalidArgumentException('non-nullable conversion_rate cannot be null');
        }
        $this->container['conversion_rate'] = $conversion_rate;

        return $this;
    }

    /**
     * Gets crypto_transaction_info
     *
     * @return \OpenAPI\Client\Model\PaymentResponseV2DtoCryptoTransactionInfoInner[]
     */
    public function getCryptoTransactionInfo()
    {
        return $this->container['crypto_transaction_info'];
    }

    /**
     * Sets crypto_transaction_info
     *
     * @param \OpenAPI\Client\Model\PaymentResponseV2DtoCryptoTransactionInfoInner[] $crypto_transaction_info crypto_transaction_info
     *
     * @return self
     */
    public function setCryptoTransactionInfo($crypto_transaction_info)
    {
        if (is_null($crypto_transaction_info)) {
            throw new \InvalidArgumentException('non-nullable crypto_transaction_info cannot be null');
        }
        $this->container['crypto_transaction_info'] = $crypto_transaction_info;

        return $this;
    }

    /**
     * Gets rate
     *
     * @return float
     */
    public function getRate()
    {
        return $this->container['rate'];
    }

    /**
     * Sets rate
     *
     * @param float $rate rate
     *
     * @return self
     */
    public function setRate($rate)
    {
        if (is_null($rate)) {
            throw new \InvalidArgumentException('non-nullable rate cannot be null');
        }
        $this->container['rate'] = $rate;

        return $this;
    }

    /**
     * Gets partner_payment_id
     *
     * @return string|null
     */
    public function getPartnerPaymentId()
    {
        return $this->container['partner_payment_id'];
    }

    /**
     * Sets partner_payment_id
     *
     * @param string|null $partner_payment_id partner_payment_id
     *
     * @return self
     */
    public function setPartnerPaymentId($partner_payment_id)
    {
        if (is_null($partner_payment_id)) {
            throw new \InvalidArgumentException('non-nullable partner_payment_id cannot be null');
        }
        $this->container['partner_payment_id'] = $partner_payment_id;

        return $this;
    }

    /**
     * Gets partner_settings
     *
     * @return \OpenAPI\Client\Model\SettingsResponseV2Dto
     */
    public function getPartnerSettings()
    {
        return $this->container['partner_settings'];
    }

    /**
     * Sets partner_settings
     *
     * @param \OpenAPI\Client\Model\SettingsResponseV2Dto $partner_settings partner_settings
     *
     * @return self
     */
    public function setPartnerSettings($partner_settings)
    {
        if (is_null($partner_settings)) {
            throw new \InvalidArgumentException('non-nullable partner_settings cannot be null');
        }
        $this->container['partner_settings'] = $partner_settings;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


